services:
  database:
    image: mysql:8.4.5
    container_name: collabai_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME:-collabai}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: collabai_pma
    restart: always
    depends_on:
      - database
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      PMA_PORT: ${DB_PORT:-3306}
    ports:
      - "8080:80"

volumes:
  mysql-data:
